// <auto-generated />
using System;
using Funeraria.Infraestructura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Funeraria.Infraestructura.Migrations
{
    [DbContext(typeof(FunerariaDbContext))]
    [Migration("20251210033115_Funeraria")]
    partial class Funeraria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Funeraria.Dominio.Entidades.ArticuloInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EstadoStock")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioCosto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EstadoStock");

                    b.ToTable("Inventario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadDisponible = 5,
                            Categoria = "Ataudes",
                            Codigo = "ATAUD-001",
                            Descripcion = "Ataúd de madera de caoba con acabado premium y herrajes dorados",
                            EstadoStock = "Normal",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8376),
                            Nombre = "Ataúd Premium Caoba",
                            PrecioCosto = 1800.00m,
                            PrecioVenta = 2500.00m,
                            StockMinimo = 2
                        },
                        new
                        {
                            Id = 2,
                            CantidadDisponible = 8,
                            Categoria = "Ataudes",
                            Codigo = "ATAUD-002",
                            Descripcion = "Ataúd económico de madera de pino",
                            EstadoStock = "Normal",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8386),
                            Nombre = "Ataúd Básico Pino",
                            PrecioCosto = 500.00m,
                            PrecioVenta = 800.00m,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = 3,
                            CantidadDisponible = 12,
                            Categoria = "Urnas",
                            Codigo = "URNA-001",
                            Descripcion = "Urna elegante de porcelana con detalles dorados",
                            EstadoStock = "Normal",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8388),
                            Nombre = "Urna de Porcelana Blanca",
                            PrecioCosto = 150.00m,
                            PrecioVenta = 250.00m,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 4,
                            CantidadDisponible = 3,
                            Categoria = "Urnas",
                            Codigo = "URNA-002",
                            Descripcion = "Urna de madera tallada a mano",
                            EstadoStock = "Critico",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8390),
                            Nombre = "Urna de Madera",
                            PrecioCosto = 120.00m,
                            PrecioVenta = 180.00m,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = 5,
                            CantidadDisponible = 25,
                            Categoria = "Flores",
                            Codigo = "FLOR-001",
                            Descripcion = "Arreglo de 24 rosas blancas naturales",
                            EstadoStock = "Normal",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8391),
                            Nombre = "Ramo de Rosas Blancas",
                            PrecioCosto = 45.00m,
                            PrecioVenta = 80.00m,
                            StockMinimo = 10
                        },
                        new
                        {
                            Id = 6,
                            CantidadDisponible = 15,
                            Categoria = "Flores",
                            Codigo = "FLOR-002",
                            Descripcion = "Corona circular de flores mixtas con moño negro",
                            EstadoStock = "Normal",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8393),
                            Nombre = "Corona Fúnebre Grande",
                            PrecioCosto = 90.00m,
                            PrecioVenta = 150.00m,
                            StockMinimo = 8
                        },
                        new
                        {
                            Id = 7,
                            CantidadDisponible = 6,
                            Categoria = "Flores",
                            Codigo = "FLOR-003",
                            Descripcion = "Cruz de 1.5m de altura con flores blancas",
                            EstadoStock = "Bajo",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8395),
                            Nombre = "Cruz de Flores",
                            PrecioCosto = 120.00m,
                            PrecioVenta = 200.00m,
                            StockMinimo = 4
                        },
                        new
                        {
                            Id = 8,
                            CantidadDisponible = 50,
                            Categoria = "Velas",
                            Codigo = "VELA-001",
                            Descripcion = "Set de 4 velas blancas de larga duración",
                            EstadoStock = "Normal",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8396),
                            Nombre = "Velas Grandes 48 horas",
                            PrecioCosto = 8.00m,
                            PrecioVenta = 15.00m,
                            StockMinimo = 20
                        },
                        new
                        {
                            Id = 9,
                            CantidadDisponible = 30,
                            Categoria = "Articulos Religiosos",
                            Codigo = "REL-001",
                            Descripcion = "Libro elegante para firmas de visitantes",
                            EstadoStock = "Normal",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8398),
                            Nombre = "Libro de Condolencias",
                            PrecioCosto = 12.00m,
                            PrecioVenta = 25.00m,
                            StockMinimo = 10
                        },
                        new
                        {
                            Id = 10,
                            CantidadDisponible = 20,
                            Categoria = "Vestimenta",
                            Codigo = "VEST-001",
                            Descripcion = "Mortaja de algodón blanco talla estándar",
                            EstadoStock = "Normal",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8400),
                            Nombre = "Mortaja Blanca Adulto",
                            PrecioCosto = 35.00m,
                            PrecioVenta = 60.00m,
                            StockMinimo = 10
                        },
                        new
                        {
                            Id = 11,
                            CantidadDisponible = 8,
                            Categoria = "Vestimenta",
                            Codigo = "VEST-002",
                            Descripcion = "Traje negro completo con corbata",
                            EstadoStock = "Normal",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8402),
                            Nombre = "Traje Formal Hombre",
                            PrecioCosto = 70.00m,
                            PrecioVenta = 120.00m,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 12,
                            CantidadDisponible = 10,
                            Categoria = "Cosmeticos",
                            Codigo = "COSM-001",
                            Descripcion = "Set completo de cosméticos para preparación",
                            EstadoStock = "Normal",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8404),
                            Nombre = "Kit de Maquillaje Mortuorio",
                            PrecioCosto = 50.00m,
                            PrecioVenta = 85.00m,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 13,
                            CantidadDisponible = 15,
                            Categoria = "Articulos Religiosos",
                            Codigo = "LIB-001",
                            Descripcion = "Libro de firmas con portada de cuero sintético negro, 80 páginas con líneas doradas",
                            EstadoStock = "Normal",
                            FechaActualizacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(8405),
                            Nombre = "Libro de Condolencias Premium",
                            PrecioCosto = 18.00m,
                            PrecioVenta = 35.00m,
                            StockMinimo = 8
                        });
                });

            modelBuilder.Entity("Funeraria.Dominio.Entidades.DocumentoLegal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntidadEmisora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsObligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaActualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("ServicioId");

                    b.ToTable("DocumentosLegales", (string)null);
                });

            modelBuilder.Entity("Funeraria.Dominio.Entidades.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Itbms")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MontoPagado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Pagada")
                        .HasColumnType("bit");

                    b.Property<string>("RutaPdf")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroFactura")
                        .IsUnique();

                    b.HasIndex("Pagada");

                    b.HasIndex("ServicioId");

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("Funeraria.Dominio.Entidades.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumeroReferencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("FechaPago");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Funeraria.Dominio.Entidades.ServicioFunerario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CedulaDifunto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("CeremoniaReligiosa")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoExpediente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("EmailFamiliar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Registrado");

                    b.Property<DateTime>("FechaFallecimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("GestionDocumentalCompleta")
                        .HasColumnType("bit");

                    b.Property<string>("LugarFallecimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreDifunto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreFamiliar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Paquete")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SalaVelacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonoFamiliar")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoExpediente")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaRegistro");

                    b.ToTable("ServiciosFunerarios", (string)null);
                });

            modelBuilder.Entity("Funeraria.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@funeraria.com",
                            FechaCreacion = new DateTime(2025, 12, 9, 22, 31, 15, 470, DateTimeKind.Local).AddTicks(856),
                            NombreCompleto = "Administrador del Sistema",
                            NombreUsuario = "admin",
                            PasswordHash = "Admin123",
                            Rol = "Administrador"
                        });
                });

            modelBuilder.Entity("Funeraria.Dominio.Entidades.DocumentoLegal", b =>
                {
                    b.HasOne("Funeraria.Dominio.Entidades.ServicioFunerario", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");
                });
#pragma warning restore 612, 618
        }
    }
}
